### ISSUE TITLE
Actualizar README: instalación, colaboración/aporte

### ISSUE THREAD

**Issue by CamilaPua** [esgaelramos/YourMoneyTrackerMail#15]
Segmentos a actualizar:
- [x] Instalación
- [x] Paso a paso para colaborar
- [x] *Explicar error (Falta de Forks en miembros del equipo)

**Comment by esgaelramos** [comment]
Se agregaron lo pasos faltantes para poder levantar el proyecto en local, igualmente un diagrama de la infra y flujo del sitio.
https://github.com/esgaelramos/YourMoneyTrackerMail/commit/11d77ef64b98a1e184e830f716747f8c64799be3
