### ISSUE TITLE
Habilitar collectstatic en GH Action

### ISSUE THREAD

**Issue by esgaelramos** [esgaelramos/YourMoneyTrackerMail#21]
- [x] Terminar de configurar entorno productivo 
- [x] Explicar funcionamiento de collectstatic
- [x] Añadir al .gitignore la carpeta de los nuevos static
- [x] Testar uso de statics (css, js)

**Comment by CamilaPua** [comment]
- Se descomentó la línea del comando en el archivo deploy-flow.yaml
``python manage.py collectstatic``
- Agrega el directorio staticfiles al .gitignore

[PR 28](https://github.com/esgaelramos/YourMoneyTrackerMail/pull/28)
