### ISSUE TITLE
GH actions - Habilitar permisos del servicio en servidor para reinicio del mismo

### ISSUE THREAD

**Issue by CamilaPua** [esgaelramos/YourMoneyTrackerMail#31]
- [x] Habilitar permisos del servicio en servidor para reinicio del mismo
- [x] Testear deploy automático

**Comment by esgaelramos** [comment]
Done! https://github.com/esgaelramos/YourMoneyTrackerMail/commit/3708e857d61a7d9661f5e6ed40435b7f65b1129e
