### ISSUE TITLE
Crear e integrar vista 404 por Django

### ISSUE THREAD

**Issue by esgaelramos** [esgaelramos/YourMoneyTrackerMail#38]
Incluye la tarea:
- [x] HTML Propio
- [x]  CSS Correspondiente
- [x] Vista, Manejo y Mapeo por Django
- [x] Prueba de funcionamiento

**Comment by esgaelramos** [comment]
Primera estructura de View y Url: https://github.com/esgaelramos/YourMoneyTrackerMail/commit/b9e4d29f65307fbeae4761806a67994d4e490865

**Comment by AndriwRC** [comment]
Estructura HTML y Estilos CSS: https://github.com/esgaelramos/YourMoneyTrackerMail/commit/a3e9b9d07edca074a991460983ed1a6d971b06e3

Corrección de font-size en desktop mode: https://github.com/esgaelramos/YourMoneyTrackerMail/commit/8bd004aebf63a5ec446bafc35d37e355eb25ab01
