### ISSUE TITLE
Integrar PyTest!

### ISSUE THREAD

**Issue by esgaelramos** [esgaelramos/YourMoneyTrackerMail#40]
La tarea incluye integrar todo lo relacionado al step test:

- [x] Instalar dependencias y librerías para pruebas
- [x] Integrar en local, incluye elección de directorio 
- [x] Crear sistema de carpetas para pruebas, idealmente como el proyecto
- [x] Configurar librería PYTEST para medición de cobertura de archivos correctos
- [x] Integrar db sqlite para pruebas no unitarias (*opcional)
- [x] Añadir step en gh action para ejecución de tests

**Comment by CamilaPua** [comment]
Done again! https://github.com/esgaelramos/YourMoneyTrackerMail/pull/43
